language: python
python:
 - "2.7"
 - "2.6"

branches:
 only:
  - master
  - development      

before_install:
        - sudo apt-get update -qq 
        - sudo apt-get install -y iverilog

install:
 - python setup.py install

script:
 - cd test_suite
 - ./test_all
