language: python
python:
 - "2.7"
 - "2.6"

branches:
 only:
  - master
  - development      
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - python setup.py install
#script:
#- python setup.py install
